# Generated by Django 3.0.7 on 2020-06-14 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_confiabilidadeempresa_indice'),
    ]

    operations = [
        migrations.AddField(
            model_name='confiabilidadeempresa',
            name='descricao',
            field=models.TextField(blank=True),
        ),
    ]
