# Generated by Django 3.0.7 on 2020-06-14 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_confiabilidadeempresa_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='confiabilidadeempresa',
            name='logo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
